version: 2.1

commands:
  run_test:
    description: "Run test"
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-composer-{{ checksum "composer.json" }}
      - run:
          name: Install composer packages
          command: |
            composer install
      - save_cache:
          key: dependency-cache-composer-{{ checksum "composer.json" }}
          paths:
            - ~/app/vendor
      - run:
          name: Do static analysis
          command: |
            vendor/bin/phpstan --memory-limit=386M
      - run:
          name: Run PHP Insights
          command: |
            php artisan insights --no-interaction --min-quality=80 --min-complexity=90 --min-architecture=75 --min-style=90
      - run:
          name: Test
          command: |
            vendor/bin/phpunit -d memory_limit=386M

jobs:
  run_test:
    working_directory: ~/app
    docker:
      - image: cimg/php:8.1.9
    steps:
      - run_test

workflows:
  version: 2
  build-deploy:
    jobs:
      - run_test:
          filters:
            tags:
              only: /^v.*/
            branches:
              only: /.*/
